## Milestone 1 Exploration
### Jennifer Tsang, Nicole Link

In [8]:
import json
import pandas as pd

## Overview of the Dataset

### Data Loading Function

In [9]:
def load_review_sample(filepath, n_rows=1000):
    """
    Loads a specific number of rows from a JSONL file and cleans the data.
    """
    print(f"Loading the first {n_rows} rows from {filepath}...")

    # The nrows argument stops pandas from reading past our limit
    df = pd.read_json(filepath, lines=True, nrows=n_rows)

    print("Done! Data is ready for EDA.")
    return df

### Reviews Dataset Overview

In [11]:
reviews_path = "../data/raw/Arts_Crafts_and_Sewing.jsonl"

df_reviews = load_review_sample(reviews_path, n_rows=1000)
df_reviews.head()

Loading the first 1000 rows from ../data/raw/Arts_Crafts_and_Sewing.jsonl...
Done! Data is ready for EDA.

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,1,Received damaged. Has hole in mold!,[[VIDEOID:2a7ad2a91afb1e17ff4a1c143f7e10a2]] R...,[{'small_image_url': 'https://m.media-amazon.c...,B095RKB9N3,B095RXT585,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-08-21 19:55:19.157,0,True
1,3,3rd one arrived scratched/dented.,3rd one that arrived damaged! I give up!,[{'small_image_url': 'https://m.media-amazon.c...,B08PNNKNSQ,B07QXN7TMP,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-06-19 05:01:15.170,0,True
2,1,Abominable. NOT COLOR SHIFT! False Advertising!,These are regular mica powders! One appears t...,[{'small_image_url': 'https://m.media-amazon.c...,B094DH11SH,B094DH11SH,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-06-06 10:22:10.828,0,True
3,2,Used 2x in 6 weeks dry as a bone.,[[VIDEOID:8644a01103c90ab8f83af816b83881be]] L...,[{'small_image_url': 'https://m.media-amazon.c...,B089YSSFD6,B087D548ZY,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-03-25 01:07:56.726,0,True
4,1,Replaced & still Defective stamps!,Lowered from a 3 star review to a 1 star bc th...,[{'small_image_url': 'https://m.media-amazon.c...,B08Z47RG56,B08Z47RG56,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,2022-02-11 22:45:07.972,1,True

In [15]:
print(df_reviews.info())
print(df_reviews.columns.tolist())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             1000 non-null   int64
 1   title              1000 non-null   str
 2   text               1000 non-null   str
 3   images             1000 non-null   object
 4   asin               1000 non-null   str
 5   parent_asin        1000 non-null   str
 6   user_id            1000 non-null   str
 7   timestamp          1000 non-null   datetime64[ms]
 8   helpful_vote       1000 non-null   int64
 9   verified_purchase  1000 non-null   bool
dtypes: bool(1), datetime64[ms](1), int64(2), object(1), str(5)
memory usage: 403.2+ KB
None
['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase']

### Metadata Overview

In [12]:
meta_file = '../data/raw/meta_Arts_Crafts_and_Sewing.jsonl'

df_meta = load_review_sample(meta_file, n_rows=1000)
df_meta.head()

Loading the first 1000 rows from ../data/raw/meta_Arts_Crafts_and_Sewing.jsonl...
Done! Data is ready for EDA.

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Amazon Home,Trapp Home Fragrance Wax Melts - No. 13 Bob's ...,4.4,108,[Includes (2) No. 13 Bob's Flower Shoppe Trapp...,[The No. 13 Bob's Flower Shoppe Home Fragrance...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Trapp,"[Arts, Crafts & Sewing, Crafting, Candle Makin...",{'Product Dimensions': '6.75 x 3.4 x 1 inches'...,B013W3MPCW,NaN
1,"Arts, Crafts & Sewing",JESEP YONG 4packs Plastic Organizer Box 24 Gri...,4.3,103,[MATERIAL & COLOR: These storage boxes are mad...,[SIZE & PACKING: the outer box size is 7.5'' L...,12.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'craft organizers and storage', 'ur...",JESEP YONG,"[Arts, Crafts & Sewing, Organization, Storage ...","{'Brand': 'JESEP YONG', 'Color': 'Clear', 'Mat...",B09B59XWTG,NaN
2,Pet Supplies,"JIESHU 2-Pack Foam Holders for centerpieces, B...",3.6,15,[The 6 suction cups at the bottom of the foam ...,[Size: 9.5 * 4.5 * 2.7 inches Ideal for manual...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],JIESHU,"[Arts, Crafts & Sewing, Crafting, Floral Arran...",{'Product Dimensions': '9.5 x 4.5 x 2.7 inches...,B0915N2NX1,NaN
3,"Arts, Crafts & Sewing",Metal Swivel Lobster Claw Clasp Split Ring Key...,3.2,35,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],NaN,"[Arts, Crafts & Sewing, Beading & Jewelry Maki...",{'Product Dimensions': '4.1 x 3.7 x 0.6 inches...,B008SNYJSU,NaN
4,"Arts, Crafts & Sewing",Sizzix Birdcage Favor Thinlits Gift Box by Dav...,4.6,464,[Thinlits dies allow you to cut intricate desi...,[Thinlits create dazzling detailed shapes for ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Sizzix,"[Arts, Crafts & Sewing, Scrapbooking & Stampin...",{'Product Dimensions': '5.38 x 4.38 x 0.13 inc...,B07Z9FH9PR,NaN

In [14]:
print(df_meta.info())
print(df_meta.columns.tolist())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    956 non-null    str
 1   title            1000 non-null   str
 2   average_rating   1000 non-null   float64
 3   rating_number    1000 non-null   int64
 4   features         1000 non-null   object
 5   description      1000 non-null   object
 6   price            602 non-null    float64
 7   images           1000 non-null   object
 8   videos           1000 non-null   object
 9   store            986 non-null    str
 10  categories       1000 non-null   object
 11  details          1000 non-null   object
 12  parent_asin      1000 non-null   str
 13  bought_together  0 non-null      float64
dtypes: float64(3), int64(1), object(6), str(4)
memory usage: 254.8+ KB
None
['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together']

## Inspection of Sample Records

## Selection and Justification of Fields for Removal

### User Reviews:
#### Fields to Keep:
- rating - float - Rating of the product (from 1.0 to 5.0).
- title - str - Title of the user review.
- text - str - Text body of the user review.
- parent_asin - str - Parent ID of the product. Note: Products with different colors, styles, sizes usually belong to the same parent ID. The “asin” in previous Amazon datasets is actually parent ID. Please use parent ID to find product meta.
- helpful_vote - int - Helpful votes of the review


#### Fields to Remove:
- asin - str - ID of the product.
- images - list - Images that users post after they have received the product. Each image has different sizes (small, medium, large), represented by the small_image_url,medium_image_url, and large_image_url respectively.
- user_id - str - ID of the reviewer
- timestamp - int - Time of the review (unix time)
- verified_purchase - bool- User purchase verification

### Metadata
#### Fields to Keep:
- main_category - str - Main category (i.e., domain) of the product.
- title - str - Name of the product.
- average_rating - float - Rating of the product shown on the product page.
- rating_number - int - Number of ratings in the product.
- features - list - Bullet-point format features of the product.
- description - list - Description of the product.
- price - float - Price in US dollars (at time of crawling).
- store - str - Store name of the product.
- categories - list - Hierarchical categories of the product.
- details - dict - Product details, including materials, brand, sizes, etc.
- parent_asin - str - Parent ID of the product.
- bought_together	- list - Recommended bundles from the websites.

#### Fields to Remove:
- images - list - Images of the product. Each image has different sizes (thumb, large, hi_res). The “variant” field shows the position of image.
- videos - list - Videos of the product including title and url.

## Text Preprocessing Decisions